# Generated by Django 6.1.1 on 2026-09-29 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0006_portfolio_challenge_portfolio_gallery_urls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Case Study Technology',
                'verbose_name_plural': 'Case Study Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('challenge', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('key_features', models.TextField(blank=True, help_text='One feature per line')),
                ('key_result', models.CharField(blank=True, max_length=260)),
                ('featured_image_url', models.CharField(blank=True, max_length=500)),
                ('featured_image_alt', models.CharField(blank=True, max_length=220)),
                ('project_url', models.URLField(blank=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=260)),
                ('seo_description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='pages.company')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='pages.industry')),
                ('primary_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='pages.servicearea')),
                ('related_services', models.ManyToManyField(blank=True, related_name='related_case_studies', to='pages.servicearea')),
                ('technologies', models.ManyToManyField(blank=True, related_name='case_studies', to='case_studies.casestudytechnology')),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['display_order', '-completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.CharField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=220)),
                ('caption', models.CharField(blank=True, max_length=260)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='case_studies.casestudy')),
            ],
            options={
                'verbose_name': 'Case Study Gallery Image',
                'verbose_name_plural': 'Case Study Gallery',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=120)),
                ('note', models.CharField(blank=True, max_length=220)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='case_studies.casestudy')),
            ],
            options={
                'verbose_name': 'Case Study Metric',
                'verbose_name_plural': 'Case Study Metrics',
                'ordering': ['display_order', 'label'],
            },
        ),
    ]
