# Generated by Django 6.1.1 on 2026-09-29 10:03

import pages.validators
from django.db import migrations, models


def media_path(value):
    if not value:
        return ''
    for prefix in ('/media/', 'media/'):
        if value.startswith(prefix):
            return value[len(prefix):]
    return value if '://' not in value and not value.startswith('/') else ''


def copy_existing_local_paths(apps, schema_editor):
    CaseStudy = apps.get_model('case_studies', 'CaseStudy')
    CaseStudyGalleryImage = apps.get_model('case_studies', 'CaseStudyGalleryImage')
    for item in CaseStudy.objects.exclude(featured_image_url=''):
        path = media_path(item.featured_image_url)
        if path:
            item.featured_image = path
            item.save(update_fields=['featured_image'])
    for item in CaseStudyGalleryImage.objects.exclude(image_url=''):
        path = media_path(item.image_url)
        if path:
            item.image = path
            item.save(update_fields=['image'])


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0002_migrate_portfolio_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='case-studies/', validators=[pages.validators.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='casestudygalleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='case-studies/gallery/', validators=[pages.validators.validate_image_upload]),
        ),
        migrations.RunPython(copy_existing_local_paths, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='casestudy',
            name='featured_image_url',
        ),
        migrations.RemoveField(
            model_name='casestudygalleryimage',
            name='image_url',
        ),
    ]
