# Generated by Django 6.1.1 on 2026-09-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('profile_photo', models.ImageField(upload_to='team/')),
                ('designation', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('joining_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['-is_featured', 'full_name'],
            },
        ),
    ]
