# Generated by Django 6.1.1 on 2026-09-28 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_accessrole_users_quotation_revised_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=220)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enquiry',
            name='landing_page',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='utm_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pages.hostingsubscription'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='projects', to='pages.employee'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='pages.employee'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('subscription', 'billing_period'), name='unique_subscription_billing_period'),
        ),
        migrations.AddField(
            model_name='newsletterdelivery',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='pages.newsletter'),
        ),
        migrations.AddField(
            model_name='newsletterdelivery',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.subscriber'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.employee'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='pages.client'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.project'),
        ),
        migrations.AddConstraint(
            model_name='newsletterdelivery',
            constraint=models.UniqueConstraint(fields=('newsletter', 'subscriber'), name='unique_newsletter_recipient'),
        ),
    ]
