# Generated by Django 6.1.1 on 2026-09-29 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_newsletterdelivery_supportticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='gallery_urls',
            field=models.TextField(blank=True, help_text='One image URL per line'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='pages.industry'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='key_features',
            field=models.TextField(blank=True, help_text='One feature per line'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='key_result',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='results',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='seo_title',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='technology_stack',
            field=models.TextField(blank=True, help_text='One technology or capability per line'),
        ),
    ]
