# Generated by Django 6.1.1 on 2026-09-29 10:03

import pages.validators
from django.db import migrations, models


def media_path(value):
    if not value:
        return ''
    for prefix in ('/media/', 'media/'):
        if value.startswith(prefix):
            return value[len(prefix):]
    return value if '://' not in value and not value.startswith('/') else ''


def copy_existing_local_paths(apps, schema_editor):
    Insight = apps.get_model('pages', 'Insight')
    TeamMember = apps.get_model('pages', 'TeamMember')
    for item in Insight.objects.exclude(image_url=''):
        path = media_path(item.image_url)
        if path:
            item.featured_image = path
            item.save(update_fields=['featured_image'])
    for item in TeamMember.objects.exclude(image_url=''):
        path = media_path(item.image_url)
        if path:
            item.profile_image = path
            item.save(update_fields=['profile_image'])


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_portfolio_challenge_portfolio_gallery_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='insights/', validators=[pages.validators.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='teammember',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='team/', validators=[pages.validators.validate_image_upload]),
        ),
        migrations.RunPython(copy_existing_local_paths, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='websitesection',
            name='page',
        ),
        migrations.DeleteModel(
            name='MediaAsset',
        ),
        migrations.DeleteModel(
            name='NavigationItem',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='image_url',
        ),
        migrations.DeleteModel(
            name='CMSPage',
        ),
        migrations.DeleteModel(
            name='WebsiteSection',
        ),
    ]
